---
title: "combined"
author: |
  | Chai Kau Yu, Davion (S2019226)
  | William Heng Chun Meng (S2005592)
  | Lim Mei Cee (17162537)
  | Kamal Suria Asri Raja (S2110703)
  | Hong Zi Shen (S2114600)
date: "`r format(Sys.time(), '%d/%m/%y')`"
output:
    prettydoc::html_pretty:
    theme: HPSTR
    highlight: github
    math: katex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE)
```

# Introduction+Clean/Preprocessing (Mei Cee)

```{r mei_cee, echo=TRUE, results='markup'}
df_country <- read.csv("models/cases_malaysia.csv", header=TRUE)
df_state <- read.csv("models/cases_state.csv", header=TRUE)
```

# Map (Zi Shen)

```{r import_libraries, message=FALSE, warning=FALSE}
if (!require("dplyr")) {
  install.packages("dplyr", repos = "https://cran.asia/")
}
if (!require("kableExtra")) {
  install.packages("kableExtra", repos = "https://cran.asia/")
}
# if (!require("lubridate"))
#   install.packages("lubridate", repos="https://cran.asia/");
if (!require("plotly")) {
  install.packages("plotly", repos = "https://cran.asia/")
}
if (!require("plyr")) {
  install.packages("plyr", repos = "https://cran.asia/")
}
if (!require("raster")) {
  install.packages("raster", repos = "https://cran.asia/")
}
if (!require("scales")) {
  install.packages("scales", repos = "https://cran.asia/")
}
if (!require("thematic")) {
  install.packages("thematic", repos = "https://cran.asia/")
}

library(dplyr)
library(kableExtra)
library(plotly)
library(plyr)
library(raster)
library(scales)
```

#### Data Ingestion

```{r data_ingestion, echo=TRUE, results='markup', result='asis'}
# covid_malaysia_endpoint <- "https://raw.githubusercontent.com/MoH-Malaysia/covid19-public/main/epidemic/cases_malasia.csv"
# covid_state_endpoint <- "https://raw.githubusercontent.com/MoH-Malaysia/covid19-public/main/epidemic/cases_state.csv"
covid_malaysia_endpoint <- "models/cases_malaysia.csv"
covid_state_endpoint <- "models/cases_state.csv"

df <- read.csv(covid_malaysia_endpoint, header = TRUE)
df_state <- read.csv(covid_state_endpoint, header = TRUE)
```

#### Data Initialization

```{r data_initialization, echo=TRUE, results='markup', result='asis'}
df_population <- data.frame(
  c("Selangor", "Sabah", "Johor", "Sarawak", "Perak", "Kedah", "Kelantan", "Pulau Pinang", "W.P. Kuala Lumpur", "Pahang", "Terengganu", "Negeri Sembilan", "Melaka", "Perlis", "W.P. Putrajaya", "W.P. Labuan"),
  c(6555400, 3833000, 3794000, 2822200, 2508900, 2194100, 1928800, 1774400, 1746600, 1684600, 1275100, 1129100, 937500, 255400, 116100, 100100)
)
colnames(df_population) <- c("NAME_1", "pop")

theme_opts <- list(theme(
  panel.grid.minor = element_blank(),
  panel.grid.major = element_blank(),
  panel.background = element_blank(),
  plot.background = element_blank(),
  axis.line = element_blank(),
  axis.text.x = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(),
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  plot.title = element_blank()
))

malaysia <- getData("GADM", country = "MYS", level = 1)
malaysia@data <- mutate(malaysia@data, NAME_1 = replace(NAME_1, NAME_1 == "Trengganu", "Terengganu"))
malaysia@data <- mutate(malaysia@data, NAME_1 = replace(NAME_1, NAME_1 == "Kuala Lumpur", "W.P. Kuala Lumpur"))
malaysia@data <- mutate(malaysia@data, NAME_1 = replace(NAME_1, NAME_1 == "Labuan", "W.P. Labuan"))
malaysia@data <- mutate(malaysia@data, NAME_1 = replace(NAME_1, NAME_1 == "Putrajaya", "W.P. Putrajaya"))
malaysia@data$id <- rownames(malaysia@data)
```

#### Data Inspection

```{r data_inspection, echo=TRUE, results='markup', result='asis'}
# Check the structure of the dataframe
str(df)
str(df_state)

# Check the dimension of the dataframe
dim(df)
dim(df_state)

# Check the first 6 rows
head(df) %>%
  kable("html") %>%
  scroll_box(width = "100%") %>%
  kable_styling(font_size = 12)
head(df_state) %>%
  kable("html") %>%
  scroll_box(width = "100%") %>%
  kable_styling(font_size = 12)

# Examine the statistics data
summary(df) %>%
  kable("html") %>%
  scroll_box(width = "100%") %>%
  kable_styling(font_size = 12)
summary(df_state) %>%
  kable("html") %>%
  scroll_box(width = "100%") %>%
  kable_styling(font_size = 12)
```

#### Handle missing/duplicate values

```{r handle_missing, echo=TRUE, results='markup', result='asis'}
# Check for the columns with missing values
colSums(is.na(df)) %>%
  kable("html") %>%
  scroll_box(width = "100%") %>%
  kable_styling(font_size = 12)
colSums(is.na(df_state)) %>%
  kable("html") %>%
  scroll_box(width = "100%") %>%
  kable_styling(font_size = 12)

# Show first few rows of the missing values
head(df[rowSums(is.na(df)) > 0, ]) %>%
  kable("html") %>%
  scroll_box(width = "100%") %>%
  kable_styling(font_size = 12)
head(df[rowSums(is.na(df_state)) > 0, ]) %>%
  kable("html") %>%
  scroll_box(width = "100%") %>%
  kable_styling(font_size = 12)

# The missing rows for df can be ignored as there are 2020 data. 2021 data contains more columns.
# There is no missing rows for df_state.

# Check for duplicate values
df[duplicated(df)]
df[duplicated(df_state)]

# There are no duplicated rows
```

#### Preprocessing

```{r preprocessing, echo=TRUE, results='markup', result='asis'}
# Change date type from String to Date
df$date <- as.Date(df$date, format = "%Y-%m-%d")
df_state$date <- as.Date(df_state$date, format = "%Y-%m-%d")
```

#### Total Cases

```{r total_cases, echo=TRUE, results='markup', class.source = 'fold-hide'}
  df_total_cases <- df_state %>%
    group_by(state) %>%
    summarise_at(vars(cases_new), list(cases_total = sum)) %>%
    mutate(cases_total = cases_total / 1000) %>%
    arrange(state) %>%
    dplyr::rename(NAME_1 = state)

  malaysia_map <- data.table::copy(malaysia)
  malaysia_map@data <- join(malaysia_map@data, df_total_cases, by = "NAME_1")
  malaysia_df <- fortify(malaysia_map)
  malaysia_df <- join(malaysia_df, malaysia_map@data, by = "id")

  # https://garthtarr.github.io/meatR/ggplot_extensions.html
  # https://rstudio-pubs-static.s3.amazonaws.com/160207_ebe47475bb7744429b9bd4c908e2dc45.html
  ggplot() +
    geom_polygon(data = malaysia_df, aes(x = long, y = lat, group = group, fill = cases_total), color = "white", size = 0.25) +
    theme(aspect.ratio = 2 / 5) +
    scale_fill_distiller(name = "No. of Total Cases (in '000)", palette = "YlOrRd", direction = 1, breaks = pretty_breaks(n = 5)) +
    labs(title = "Total Cases Since Day 1") +
    theme_opts


  df_total_cases <- df_state %>%
    group_by(state) %>%
    summarise_at(vars(cases_new), list(cases_total = sum)) %>%
    arrange(desc(cases_total))
```

#### Infection Rate

```{r infection_rate, echo=TRUE, results='markup', class.source = 'fold-hide'}
  df_infection_rate <- df_state %>%
    group_by(state) %>%
    summarise_at(vars(cases_new), list(cases_total = sum)) %>%
    dplyr::rename(NAME_1 = state) %>%
    join(df_population, by = "NAME_1") %>%
    mutate(rate = cases_total / pop) %>%
    arrange(NAME_1)

  malaysia_map <- data.table::copy(malaysia)
  malaysia_map@data <- join(malaysia_map@data, df_infection_rate, by = "NAME_1")
  malaysia_df <- fortify(malaysia_map)
  malaysia_df <- join(malaysia_df, malaysia_map@data, by = "id")

  # https://garthtarr.github.io/meatR/ggplot_extensions.html
  # https://rstudio-pubs-static.s3.amazonaws.com/160207_ebe47475bb7744429b9bd4c908e2dc45.html
  ggplot() +
    geom_polygon(data = malaysia_df, aes(x = long, y = lat, group = group, fill = rate), color = "white", size = 0.25) +
    theme(aspect.ratio = 2 / 5) +
    scale_fill_distiller(name = "No. of Total Cases (%)", palette = "YlOrRd", direction = 1, breaks = pretty_breaks(n = 5), labels = percent) +
    labs(title = "Infection Rate based on Total Population") +
    theme_opts

  df_infection_rate <- df_state %>%
    group_by(state) %>%
    summarise_at(vars(cases_new), list(cases_total = sum)) %>%
    dplyr::rename(NAME_1 = state) %>%
    join(df_population, by = "NAME_1") %>%
    dplyr::rename(state = NAME_1) %>%    
    mutate(rate = cases_total / pop) %>%
    arrange(desc(rate)) %>%
    mutate(rate = paste0(round(cases_total / pop * 100, 2), "%"))
```

# Arima (Kamal)

```{r kamal, echo=TRUE, results='markup'}
df_country <- read.csv("models/cases_malaysia.csv", header=TRUE)
df_state <- read.csv("models/cases_state.csv", header=TRUE)
```

# Mixed Model (Davion)

```{r davion, echo=TRUE, results='markup'}
df_country <- read.csv("models/cases_malaysia.csv", header=TRUE)
df_state <- read.csv("models/cases_state.csv", header=TRUE)
```

# Closing (William)

```{r william, echo=TRUE, results='markup'}
df_country <- read.csv("models/cases_malaysia.csv", header=TRUE)
df_state <- read.csv("models/cases_state.csv", header=TRUE)
```


